### PR TITLE
117 Updates Windows installation manual

### PR DESCRIPTION
**Pull request by mmanna-sapfgl**
As per queries to ClamAV user forum and the information compiled, the Windows Installation manual has been updated for review.

### CODE REVIEW

**Comment by mmanna-sapfgl** [comment]
Micah,

I was inclined not to use Windows Service related instructions. The reason is that different users can have their own flavours of wrapping and deploying windows services (with no standard name to map freshclam.exe and clamd.exe). Additionally, each organisation has their own way of controlling accessing privileges to services. In fact, Windows Services in my opinion, is somewhat outside ClamAV context.

Let me know your thoughts.

Regards,
MAnna

**Comment by micah-at-talos** [comment]
> Micah, I was inclined not to use Windows Service related instructions. The reason is that different users can have their own flavours of wrapping and deploying windows services (with no standard name to map freshclam.exe and clamd.exe). Additionally, each organisation has their own way of controlling accessing privileges to services. In fact, Windows Services in my opinion, is somewhat outside ClamAV context. Let me know your thoughts. Regards, MAnna 

You're probably right.  However, I don't think that setting up Windows Services is common knowledge.  I certainly am not very familiar with it.  I was hoping we could provide something for users to get started.  Then again, maybe it should wait until we can build-in support for running freshclam and clamd as services so we don't end up with documentation for two completely different processes.

**Comment by mmanna-sapfgl** [comment]
> > Micah, I was inclined not to use Windows Service related instructions. The reason is that different users can have their own flavours of wrapping and deploying windows services (with no standard name to map freshclam.exe and clamd.exe). Additionally, each organisation has their own way of controlling accessing privileges to services. In fact, Windows Services in my opinion, is somewhat outside ClamAV context. Let me know your thoughts. Regards, MAnna
> 
> You're probably right. However, I don't think that setting up Windows Services is common knowledge. I certainly am not very familiar with it. I was hoping we could provide something for users to get started. Then again, maybe it should wait until we can build-in support for running freshclam and clamd as services so we don't end up with documentation for two completely different processes.

Sure thing  - Are yo proposing that we postpone this PR, or create a separate ticket for WIndows Service docs?

**Comment by mmanna-sapfgl** [comment]
> > > Micah, I was inclined not to use Windows Service related instructions. The reason is that different users can have their own flavours of wrapping and deploying windows services (with no standard name to map freshclam.exe and clamd.exe). Additionally, each organisation has their own way of controlling accessing privileges to services. In fact, Windows Services in my opinion, is somewhat outside ClamAV context. Let me know your thoughts. Regards, MAnna
> > 
> > 
> > You're probably right. However, I don't think that setting up Windows Services is common knowledge. I certainly am not very familiar with it. I was hoping we could provide something for users to get started. Then again, maybe it should wait until we can build-in support for running freshclam and clamd as services so we don't end up with documentation for two completely different processes.
> 
> Sure thing - Are yo proposing that we postpone this PR, or create a separate ticket for WIndows Service docs?

@micah-at-talos  Just trying to catch up with this. Are you suggesting that the doc won't be needed anymore? Or, are we having different docs for Windows services and Windows installation upgrade?

**Comment by micah-at-talos** [comment]
> @micah-at-talos Just trying to catch up with this. Are you suggesting that the doc won't be needed anymore? Or, are we having different docs for Windows services and Windows installation upgrade?

@mmanna-sapfgl  I'm of two mind on this.  I like the changes included in this pull-request.  However, my original intent for https://github.com/Cisco-Talos/clamav-faq/issues/117 was to add instructions for how to run `clamd` and `freshclam` as services on Windows.  Seeing as I don't know how you have set it up, maybe you're right and it doesn't make sense to add to the documentation.  I don't know.  

If you're up for it, can you briefly describe your process and your recommendations and we'll decide whether or not it makes sense to add to the manual for everyone.

**Comment by finchy** [comment]
closing for inactivity.

**Comment by mmanna-sapfgl** [comment]
@micahsnyder Hello - did we decide not to merge this PR? If there are corrects need to be made, I can do so. Sorry for following up so late. I only saw that @finchy closed the PR.

**Pull request closed without merging**
